### ISSUE TITLE
Refactoriza esValida

### ISSUE THREAD

**Issue by lmagarin** [i02lomom/EstructurasDeDatos#4]
if(return esValida(Integer.parseInt(array[0]),
                    Integer.parseInt(array[1])-1,
                    Integer.parseInt(array[2])))  
        //      return true;
            //return false;

en vez de 
if(esValida(Integer.parseInt(array[0]),
                    Integer.parseInt(array[1])-1,
                    Integer.parseInt(array[2])))  
                return true;
            return false;

**Comment by i02lomom** [comment]
Vale, creo que así está mejor ¿no?

private boolean esValida(String cadena){
        String[] array=obtenerArrayDiaMesAnno(cadena);
        try {
            return (esValida(Integer.parseInt(array[0]),
                    Integer.parseInt(array[1])-1,
                    Integer.parseInt(array[2])));  
        } catch (NumberFormatException e) {
            return false;
        }
    }

**Comment by lmagarin** [comment]
Ahí, ahí...
