### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by lmagarin** [i02lomom/EstructurasDeDatos#5]
Tienes el Locale(es,es) sólo en el constructor por defecto, por lo que tienes que actualizarlo en 
- getDiaDeLaSemana()

O lo colocas por defecto 
- Locale.setDefault(Locale)

o en el segundo constructor.
Por si... revisa los bloques estáticos:
- http://javajavallavero.blogspot.com.es/2011/10/bloques-de-inicializacion-y-bloques.html
##

**Comment by i02lomom** [comment]
En el segundo constructor he hecho esto:

calendar= new GregorianCalendar(locale);
calendar.set(anno, mes, dia);

Aún teniendo el locale en español si hacemos un

fecha.getFecha().getTime()

Saldrá en inglés. Solo saldrá en castellano si hacemos algo así:

calendar.getDisplayName(Calendar.DAY_OF_WEEK, Calendar.LONG, locale);

Por tanto no tiene sentido crear los gregorianCalendar con un locale concreto, pero si nos conviene tener una variable estática con el locale para cuando nos haga falta
![captura](https://cloud.githubusercontent.com/assets/15675731/14156797/8adb84e6-f6c8-11e5-82ee-bc480c8cb8a7.PNG)

**Comment by i02lomom** [comment]
Puesto que ya tengo todos los constructores de GregorianCalendar con el Locale en español doy por cerrado el issue.
